MODULE TYPES

! Definitions of various derived data types
 
USE PRECISION_PARAMETERS

IMPLICIT NONE
CHARACTER(255), PARAMETER :: typeid='$Id$'
CHARACTER(255), PARAMETER :: typerev='$Revision$'
CHARACTER(255), PARAMETER :: typedate='$Date$'

TYPE PARTICLE_CLASS_TYPE
   CHARACTER(30) :: ID,SPEC_ID,QUANTITIES(10),SMOKEVIEW_BAR_LABEL(10)
   CHARACTER(60) :: SMOKEVIEW_LABEL(10)
   REAL(EB) :: DENSITY,H_V,C_P,TMP_V,TMP_MELT,FTPR,MASS_PER_VOLUME, &
               HEAT_OF_COMBUSTION,ADJUST_EVAPORATION, &
               LIFETIME,DIAMETER,MINIMUM_DIAMETER,MAXIMUM_DIAMETER,GAMMA,KILL_RADIUS, &
               TMP_INITIAL,SIGMA,X1,X2,Y1,Y2,Z1,Z2,DT_INSERT,GAMMA_VAP,&
               VERTICAL_VELOCITY,HORIZONTAL_VELOCITY, &
!rm ->
               VEG_SV,VEG_MOISTURE,VEG_CHAR_FRACTION,VEG_DRAG_COEFFICIENT,VEG_BULK_DENSITY, &
               VEG_DENSITY,VEG_BURNING_RATE_MAX,VEG_DEHYDRATION_RATE_MAX,VEG_INITIAL_TEMPERATURE
!rm <-
   REAL(EB), POINTER, DIMENSION(:) :: R_CDF,CDF,W_CDF,INSERT_CLOCK,KWR
   REAL(EB), POINTER, DIMENSION(:,:) :: WQABS,WQSCA
   INTEGER :: N_INITIAL,SAMPLING,N_INSERT,SPEC_INDEX,N_QUANTITIES,QUANTITIES_INDEX(10),EVAP_INDEX=0,RGB(3)
   INTEGER,  POINTER, DIMENSION(:) :: IL_CDF,IU_CDF
   LOGICAL :: STATIC=.FALSE.,WATER=.FALSE.,FUEL=.FALSE.,MASSLESS,TREE=.FALSE.,MONODISPERSE=.FALSE.,EVAPORATE=.TRUE.
!rm ->
   LOGICAL VEG_REMOVE_CHARRED
!rm <-
END TYPE PARTICLE_CLASS_TYPE

TYPE (PARTICLE_CLASS_TYPE), DIMENSION(:), ALLOCATABLE, TARGET :: PARTICLE_CLASS

TYPE DROPLET_TYPE
   REAL(EB) :: X,Y,Z,TMP,U,V,W,R,PWT,A_X,A_Y,A_Z,T,RE=0._EB, &
!rm ->
               VEG_KAPPA,VEG_EMISS,VEG_PACKING_RATIO,VEG_FUEL_MASS,VEG_MOIST_MASS,VEG_REP
!rm <-
   INTEGER  :: IOR,CLASS,TAG,WALL_INDEX=0
   LOGICAL  :: SHOW,SPLAT=.FALSE.
END TYPE DROPLET_TYPE

TYPE WALL_TYPE
   REAL(EB), POINTER, DIMENSION(:) :: TMP_S, LAYER_THICKNESS,X_S
   REAL(EB), POINTER, DIMENSION(:,:) :: ILW,RHO_S
   INTEGER, POINTER, DIMENSION(:) :: N_LAYER_CELLS
   LOGICAL :: SHRINKING, BURNAWAY
END TYPE WALL_TYPE
 
TYPE SPECIES_TYPE
   REAL(EB), DIMENSION(0:500) :: MU,K,D,CP,H_G,RCP
   REAL(EB) :: MW,YY0,RCON,MAXMASS,MASS_EXTINCTION_COEFFICIENT
   LOGICAL :: ABSORBING
   REAL(EB), POINTER, DIMENSION(:,:,:) :: KAPPA
   CHARACTER(30):: ID,FORMULA
   INTEGER :: NKAP_MASS,NKAP_TEMP,MODE
END TYPE SPECIES_TYPE

TYPE (SPECIES_TYPE), DIMENSION(:), ALLOCATABLE, TARGET :: SPECIES

TYPE REACTION_TYPE
   CHARACTER(30) :: FUEL,OXIDIZER,NAME
   REAL(EB) :: EPUMO2,HEAT_OF_COMBUSTION,BOF,E, &
      NU_N2,NU_O2,NU_SOOT,NU_CO,NU_H2,NU_CO2,NU_H2O,N_F=0,N_O=0, &
      Y_O2_INFTY,Y_N2_INLET=0,Y_N2_INFTY=0,Y_F_INLET,MW_FUEL,NU_OTHER,MW_OTHER, &
      CO_YIELD,SOOT_YIELD,H2_YIELD, SOOT_H_FRACTION, &
      CRIT_FLAME_TMP,Y_F_LFL,Y_O2_LL,O2_F_RATIO=0,Z_F=0,Z_F_CONS=0
   REAL(EB), DIMENSION(MAX_SPECIES) :: NU=0,N=0
   INTEGER :: I_FUEL=0,I_OXIDIZER=0,MODE
   LOGICAL :: IDEAL
   CHARACTER(100) :: FYI='null'
END TYPE REACTION_TYPE

TYPE (REACTION_TYPE), DIMENSION(:), ALLOCATABLE, TARGET :: REACTION
 
TYPE MATERIAL_TYPE
   REAL(EB) :: K_S,C_S,HEAT_OF_COMBUSTION,RHO_S,EMISSIVITY,DIFFUSIVITY,KAPPA_S,MOISTURE_FRACTION,ADJUST_BURN_RATE,TMP_BOIL
   INTEGER :: PYROLYSIS_MODEL
   CHARACTER(30) :: RAMP_K_S,RAMP_C_S
   INTEGER :: N_REACTIONS,PROP_INDEX=-1,CABL_INDEX=-1
   REAL(EB), DIMENSION(1:MAX_REACTIONS) :: NU_RESIDUE,NU_FUEL,NU_WATER,A,E,H_R,N_S,N_T
   REAL(EB), DIMENSION(1:MAX_REACTIONS) :: TMP_REF,TMP_IGN,TMP_THR
   INTEGER, DIMENSION(1:MAX_REACTIONS) :: RESIDUE_MATL_INDEX
   CHARACTER(30), DIMENSION(1:MAX_REACTIONS) :: RESIDUE_MATL_NAME
   CHARACTER(100) :: FYI='null'
   LOGICAL :: USER_DEFINED=.TRUE.,CONDUIT=.FALSE.,AIR=.FALSE.
END TYPE MATERIAL_TYPE

TYPE (MATERIAL_TYPE), DIMENSION(:), ALLOCATABLE, TARGET :: MATERIAL

TYPE SURFACE_TYPE
   REAL(EB) :: SLIP_FACTOR,TMP_FRONT,TMP_INNER,VEL,PLE,Z0,CONVECTIVE_HEAT_FLUX, &
               VOLUME_FLUX,HRRPUA,MLRPUA,T_IGN,SURFACE_DENSITY,CELL_SIZE_FACTOR, &
               E_COEFFICIENT,TEXTURE_WIDTH,TEXTURE_HEIGHT,THICKNESS,EXTERNAL_FLUX,TMP_BACK, &
               DXF,DXB,MASS_FLUX_TOTAL,STRETCH_FACTOR,PARTICLE_MASS_FLUX,EMISSIVITY,MAX_PRESSURE,&
               TMP_IGN,H_V,REGRID_FACTOR
   REAL(EB), POINTER, DIMENSION(:) :: DX,RDX,RDXN,X_S,DX_WGT
   REAL(EB), DIMENSION(0:MAX_SPECIES) :: MASS_FRACTION,MASS_FLUX
   REAL(EB), DIMENSION(-3:MAX_SPECIES) :: TAU
   INTEGER,  DIMENSION(-3:MAX_SPECIES) :: RAMP_INDEX=0
   INTEGER, DIMENSION(3) :: RGB
   REAL(EB) :: TRANSPARENCY
   REAL(EB), DIMENSION(2) :: VEL_T
   INTEGER, DIMENSION(2) :: LEAK_PATH,DUCT_PATH
   INTEGER :: THERMAL_BC_INDEX,NPPC,SPECIES_BC_INDEX,SURF_TYPE,N_CELLS,PART_INDEX,PROP_INDEX=-1,CABL_INDEX=-1
   INTEGER :: PYROLYSIS_MODEL
   INTEGER :: N_LAYERS,N_MATL
   INTEGER, POINTER, DIMENSION(:) :: N_LAYER_CELLS,LAYER_INDEX,MATL_INDEX
   INTEGER, DIMENSION(MAX_LAYERS,MAX_MATERIALS) :: LAYER_MATL_INDEX
   INTEGER, DIMENSION(MAX_LAYERS) :: N_LAYER_MATL
   INTEGER, POINTER, DIMENSION(:,:) :: RESIDUE_INDEX
   REAL(EB), POINTER, DIMENSION(:) :: MIN_DIFFUSIVITY
   REAL(EB), DIMENSION(MAX_LAYERS) :: LAYER_THICKNESS, LAYER_DENSITY
   CHARACTER(30), POINTER, DIMENSION(:) :: MATL_NAME
   CHARACTER(30), DIMENSION(MAX_LAYERS,MAX_MATERIALS) :: LAYER_MATL_NAME
   REAL(EB), DIMENSION(MAX_LAYERS,MAX_MATERIALS) :: LAYER_MATL_FRAC
   LOGICAL :: BURN_AWAY,ADIABATIC,THERMALLY_THICK,INTERNAL_RADIATION,SHRINK,POROUS=.FALSE.,USER_DEFINED=.TRUE.
   INTEGER :: GEOMETRY,BACKING,PROFILE
   CHARACTER(30) :: PART_ID,RAMP_Q,RAMP_V,RAMP_T
   CHARACTER(30), DIMENSION(0:MAX_SPECIES) :: RAMP_MF
   CHARACTER(60) :: TEXTURE_MAP
   CHARACTER(100) :: FYI='null'
END TYPE SURFACE_TYPE

TYPE (SURFACE_TYPE), DIMENSION(:), ALLOCATABLE, TARGET :: SURFACE

TYPE OMESH_TYPE
   REAL(EB), POINTER, DIMENSION(:,:,:) :: RHO,RHOS,U,V,W,US,VS,WS,H,DUDT,DVDT,DWDT
   REAL(EB), POINTER, DIMENSION(:,:,:,:) :: YY,YYS
   INTEGER, POINTER, DIMENSION(:,:) :: IJKW
   INTEGER, POINTER, DIMENSION(:) :: BOUNDARY_TYPE
   TYPE(WALL_TYPE), POINTER, DIMENSION(:) :: WALL
   TYPE(DROPLET_TYPE), POINTER, DIMENSION(:) :: DROPLET
   INTEGER :: N_DROP_ORPHANS,N_DROP_ORPHANS_DIM,N_DROP_ADOPT
   REAL(EB), POINTER, DIMENSION(:) :: &
         REAL_SEND_PKG1,REAL_SEND_PKG2,REAL_SEND_PKG3,REAL_SEND_PKG4,REAL_SEND_PKG5,REAL_SEND_PKG6,REAL_SEND_PKG7, &
         REAL_RECV_PKG1,REAL_RECV_PKG2,REAL_RECV_PKG3,REAL_RECV_PKG4,REAL_RECV_PKG5,REAL_RECV_PKG6,REAL_RECV_PKG7
   INTEGER , POINTER, DIMENSION(:) :: INTG_SEND_PKG1,INTG_RECV_PKG1
   LOGICAL , POINTER, DIMENSION(:) :: LOGI_SEND_PKG1,LOGI_RECV_PKG1
END TYPE OMESH_TYPE
 
TYPE OBSTRUCTION_TYPE
   CHARACTER(30) :: DEVC_ID='null',CTRL_ID='null'
   INTEGER, DIMENSION(-3:3) :: IBC=0
   LOGICAL, DIMENSION(-3:3) :: SHOW_BNDF=.TRUE.
   INTEGER, DIMENSION(3) :: RGB=(/0,0,0/)
   INTEGER, DIMENSION(3) :: DIMENSIONS=0
   REAL(EB) :: TRANSPARENCY = 1._EB
   REAL(EB), DIMENSION(3) :: TEXTURE=0._EB
   REAL(EB) :: X1=0._EB,X2=1._EB,Y1=0._EB,Y2=1._EB,Z1=0._EB,Z2=1._EB,T_REMOVE=1.E6_EB,MASS=1.E6_EB
   REAL(EB), DIMENSION(3) :: FDS_AREA=-1._EB,INPUT_AREA=-1._EB
   INTEGER :: I1=-1,I2=-1,J1=-1,J2=-1,K1=-1,K2=-1,COLOR_INDICATOR=-1,TYPE_INDICATOR=-1,ORDINAL=0,DEVC_INDEX=-1,CTRL_INDEX=-1
   LOGICAL :: SAWTOOTH=.TRUE.,HIDDEN=.FALSE.,PERMIT_HOLE=.TRUE.,ALLOW_VENT=.TRUE.,CONSUMABLE=.FALSE.,REMOVABLE=.FALSE., &
              THIN=.FALSE.,HOLE_FILLER=.FALSE.
END TYPE OBSTRUCTION_TYPE
 
TYPE VENTS_TYPE
   INTEGER :: I1=-1,I2=-1,J1=-1,J2=-1,K1=-1,K2=-1,BOUNDARY_TYPE=0,IOR=0,IBC=0,DEVC_INDEX=-1,CTRL_INDEX=-1, &
              COLOR_INDICATOR=99,TYPE_INDICATOR=0,ORDINAL=0,PRESSURE_RAMP_INDEX=0
   INTEGER, DIMENSION(3) :: RGB=-1
   REAL(EB) :: TRANSPARENCY = 1._EB
   REAL(EB), DIMENSION(3) :: TEXTURE=0._EB
   REAL(EB) :: X1=0._EB,X2=0._EB,Y1=0._EB,Y2=0._EB,Z1=0._EB,Z2=0._EB,FDS_AREA=0._EB,TOTAL_INPUT_AREA=0._EB, &
               X0=-9.E6_EB,Y0=-9.E6_EB,Z0=-9.E6_EB,FIRE_SPREAD_RATE=0.05_EB,INPUT_AREA=0._EB,TMP_EXTERIOR=-1000._EB, &
               MASS_FRACTION(MAX_SPECIES)=-1._EB,DYNAMIC_PRESSURE=0._EB
   LOGICAL :: ACTIVATED=.TRUE.
   CHARACTER(30) :: DEVC_ID='null',CTRL_ID='null'
END TYPE VENTS_TYPE
 
TYPE TABLES_TYPE
   INTEGER :: NUMBER_ROWS,NUMBER_COLUMNS
   REAL(EB), POINTER, DIMENSION (:,:) :: TABLE_DATA
END TYPE TABLES_TYPE

TYPE (TABLES_TYPE), DIMENSION(:), ALLOCATABLE, TARGET :: TABLES
   
TYPE RAMPS_TYPE
   REAL(EB) :: SPAN,DT,T_MIN,T_MAX,VALUE
   REAL(EB), POINTER, DIMENSION(:) :: INDEPENDENT_DATA,DEPENDENT_DATA,INTERPOLATED_DATA
   INTEGER :: NUMBER_DATA_POINTS,NUMBER_INTERPOLATION_POINTS,DEVC_INDEX=-1,CTRL_INDEX=-1
   CHARACTER(30) :: DEVC_ID='null',CTRL_ID='null'
END TYPE RAMPS_TYPE

TYPE (RAMPS_TYPE), DIMENSION(:), ALLOCATABLE, TARGET :: RAMPS

TYPE HUMAN_TYPE
   CHARACTER(60) :: NODE_NAME
   CHARACTER(30) :: FFIELD_NAME
   REAL(EB) :: X,Y,Z,U,V,W,F_X,F_Y,X_old,Y_old,X_group,Y_group
   REAL(EB) :: UBAR, VBAR, UBAR_Center, VBAR_Center
   REAL(EB) :: Speed, Radius, Mass, Tpre, Tau, Eta, Ksi, Tdet
   REAL(EB) :: r_torso, r_shoulder, d_shoulder, angle, torque, m_iner
   REAL(EB) :: tau_iner, angle_old, omega
   REAL(EB) :: A, B, C_Young, Gamma, Kappa, Lambda, Commitment
   REAL(EB) :: SumForces, IntDose, DoseCrit1, DoseCrit2, SumForces2
   REAL(EB) :: TempMax1, FluxMax1, TempMax2, FluxMax2
   REAL(EB) :: P_detect_tot, v0_fac
   INTEGER  :: IOR, ILABEL, COLOR_INDEX, INODE, IMESH, IPC, IEL, I_FFIELD
   INTEGER  :: GROUP_ID, DETECT1, GROUP_SIZE, I_Target, I_DoorAlgo
   LOGICAL  :: SHOW, NewRnd
END TYPE HUMAN_TYPE

TYPE HUMAN_GRID_TYPE
! (x,y,z) Centers of the grid cells in the main evacuation meshes
! SOOT_DENS: Smoke density at the center of the cell (mg/m3)
! FED_CO_CO2_O2: Purser's FED for co, co2, and o2
   REAL(EB) :: X,Y,Z,SOOT_DENS,FED_CO_CO2_O2,TMP_G,RADINT
   INTEGER :: N, N_old, IGRID, IHUMAN, ILABEL
! IMESH: (x,y,z) which fire mesh, if any
! II,JJ,KK: Fire mesh cell reference
   INTEGER  :: IMESH,II,JJ,KK
END TYPE HUMAN_GRID_TYPE
 
TYPE OUTPUT_QUANTITY_TYPE
   CHARACTER(30) :: NAME='null',SHORT_NAME='null',UNITS='null'
   REAL(EB) :: AMBIENT_VALUE=0._EB
   INTEGER :: IOR=0,CELL_POSITION=1
   LOGICAL :: SLCF_APPROPRIATE=.TRUE., BNDF_APPROPRIATE=.FALSE., ISOF_APPROPRIATE=.TRUE., PART_APPROPRIATE=.FALSE., &
              MIXTURE_FRACTION_ONLY=.FALSE.,INTEGRATED=.FALSE.,SOLID_PHASE=.FALSE.,GAS_PHASE=.TRUE.,INTEGRATED_DROPLETS=.FALSE., &
              MASS_FRACTION=.FALSE.,SPEC_ID_REQUIRED=.FALSE.,PART_ID_REQUIRED=.FALSE.,INSIDE_SOLID=.FALSE.,MATL_ID_REQUIRED=.FALSE.
END TYPE OUTPUT_QUANTITY_TYPE

TYPE (OUTPUT_QUANTITY_TYPE), DIMENSION(:), ALLOCATABLE, TARGET :: OUTPUT_QUANTITY

TYPE SLICE_TYPE
   INTEGER :: I1,I2,J1,J2,K1,K2,INDEX,SPEC_INDEX=0,PART_INDEX=0
   LOGICAL :: RLE
   REAL(FB), DIMENSION(2) :: MINMAX
   LOGICAL :: TWO_BYTE
   CHARACTER(60) :: SMOKEVIEW_LABEL
   CHARACTER(30) :: SMOKEVIEW_BAR_LABEL
END TYPE SLICE_TYPE

TYPE BOUNDARY_FILE_TYPE
   INTEGER :: INDEX,PROP_INDEX,SPEC_INDEX=0,PART_INDEX=0
   CHARACTER(60) :: SMOKEVIEW_LABEL
   CHARACTER(30) :: SMOKEVIEW_BAR_LABEL
END TYPE BOUNDARY_FILE_TYPE

TYPE (BOUNDARY_FILE_TYPE), DIMENSION(:), ALLOCATABLE, TARGET :: BOUNDARY_FILE

TYPE ISOSURFACE_FILE_TYPE
   INTEGER :: INDEX=1,INDEX2=0,REDUCE_TRIANGLES=1,N_VALUES=1,SPEC_INDEX=0,SPEC_INDEX2=0
   REAL(FB) :: VALUE(10)
   CHARACTER(60) :: SMOKEVIEW_LABEL
   CHARACTER(30) :: SMOKEVIEW_BAR_LABEL
END TYPE ISOSURFACE_FILE_TYPE

TYPE (ISOSURFACE_FILE_TYPE), DIMENSION(:), ALLOCATABLE, TARGET :: ISOSURFACE_FILE

TYPE PROFILE_TYPE
   REAL(EB) :: X,Y,Z
   INTEGER  :: IOR,IW,ORDINAL,MESH
   CHARACTER(30) :: ID,QUANTITY
END TYPE PROFILE_TYPE

TYPE (PROFILE_TYPE), DIMENSION(:), ALLOCATABLE, TARGET :: PROFILE

TYPE INITIALIZATION_TYPE
   REAL(EB) :: TEMPERATURE,DENSITY,MASS_FRACTION(MAX_SPECIES),X1,X2,Y1,Y2,Z1,Z2
   LOGICAL :: ADJUST_DENSITY=.FALSE., ADJUST_TEMPERATURE=.FALSE.
END TYPE INITIALIZATION_TYPE

TYPE (INITIALIZATION_TYPE), DIMENSION(:), ALLOCATABLE, TARGET :: INITIALIZATION

TYPE P_ZONE_TYPE
   REAL(EB) :: X1,X2,Y1,Y2,Z1,Z2
   REAL(EB), DIMENSION(0:MAX_LEAK_PATHS) :: LEAK_AREA
   CHARACTER(30) :: ID
END TYPE P_ZONE_TYPE

TYPE (P_ZONE_TYPE), DIMENSION(:), ALLOCATABLE, TARGET :: P_ZONE

CONTAINS

SUBROUTINE GET_REV_type(MODULE_REV,MODULE_DATE)
INTEGER,INTENT(INOUT) :: MODULE_REV
CHARACTER(255),INTENT(INOUT) :: MODULE_DATE

WRITE(MODULE_DATE,'(A)') typerev(INDEX(typerev,':')+1:LEN_TRIM(typerev)-2)
READ (MODULE_DATE,'(I5)') MODULE_REV
WRITE(MODULE_DATE,'(A)') typedate

END SUBROUTINE GET_REV_type

END MODULE TYPES
 

MODULE MESH_VARIABLES
 
! Data structure for mesh-dependent variables
 
USE PRECISION_PARAMETERS
USE TYPES
IMPLICIT NONE

CHARACTER(255), PARAMETER :: meshid='$Id$'
CHARACTER(255), PARAMETER :: meshrev='$Revision$'
CHARACTER(255), PARAMETER :: meshdate='$Date$'
 
TYPE MESH_TYPE
 
   REAL(EB), POINTER, DIMENSION(:,:,:) :: &
            U,V,W,US,VS,WS,DDDT,D,DS,H,HP,FVX,FVY,FVZ,RHO,RHOS, &
            MU,TMP,Q,Q_AVG,FRHO,KAPPA,QR,QR_W,UII,RSUM,Z_SUM,Y_SUM,D_VAP
            
   REAL(EB), POINTER, DIMENSION(:,:,:,:) :: FRHOYY
 
   REAL(EB), POINTER, DIMENSION(:,:,:,:) :: YY,YYS,DEL_RHO_D_DEL_Y,AVG_DROP_DEN,AVG_DROP_TMP,AVG_DROP_RAD
   REAL(EB), POINTER, DIMENSION(:,:) :: UVW_GHOST
 
   REAL(EB) :: POIS_PTB,POIS_ERR
   REAL(EB), POINTER, DIMENSION(:) :: SAVE1,SAVE2,WORK
   REAL(EB), POINTER, DIMENSION(:,:,:) :: PRHS
   REAL(EB), POINTER, DIMENSION(:,:) :: BXS,BXF,BYS,BYF,BZS,BZF, BXST,BXFT,BYST,BYFT,BZST,BZFT
   INTEGER :: LSAVE,LWORK,LBC,MBC,NBC,ITRN,JTRN,KTRN,IPS
   REAL(EB), POINTER, DIMENSION(:) :: P_0,RHO_0,TMP_0,D_PBAR_DT,D_PBAR_S_DT,U_LEAK,U_DUCT
   REAL(EB), POINTER, DIMENSION(:,:) :: PBAR,PBAR_S,R_PBAR,LEAK_AREA,FDS_LEAK_AREA
   INTEGER, POINTER, DIMENSION(:,:,:) :: PRESSURE_ZONE 
   INTEGER, POINTER, DIMENSION(:) :: PRESSURE_ZONE_WALL
   REAL(EB), POINTER, DIMENSION(:,:,:) :: WORK1,WORK2,WORK3,WORK4,WORK5,WORK6,WORK7
   
   REAL(EB), POINTER, DIMENSION(:) :: SMIN_SAVE,SMAX_SAVE
   REAL(EB), POINTER, DIMENSION(:,:,:) :: SCALAR_SAVE1
   REAL(EB), POINTER, DIMENSION(:,:,:,:) :: SCALAR_SAVE2,SCALAR_SAVE3
   
   REAL(EB), POINTER, DIMENSION(:) :: WALL_WORK1,WALL_WORK2
   REAL(FB), POINTER, DIMENSION(:,:,:,:) :: QQ
   REAL(FB), POINTER, DIMENSION(:,:) :: PP,PPN
   INTEGER, POINTER, DIMENSION(:,:) :: IBK
   INTEGER, POINTER, DIMENSION(:,:,:) :: IBLK
 
   REAL(EB) :: DT,DTOLD,DTNEXT,DTINT,DTBX
   REAL(EB) :: CFL,DIVMX,DIVMN,VN,RESMAX
   INTEGER  :: ICFL,JCFL,KCFL,IMX,JMX,KMX,IMN,JMN,KMN, I_VN,J_VN,K_VN,IRM,JRM,KRM
 
   INTEGER :: N_EDGES
   INTEGER, POINTER, DIMENSION(:,:) :: IJKE,EDGE_INDEX
   REAL(EB), POINTER, DIMENSION(:) :: TAU_E,OME_E
   INTEGER, POINTER, DIMENSION(:,:) :: EDGE_TYPE
 
   INTEGER :: IBAR,JBAR,KBAR,IBAR2,JBAR2,KBAR2,IBM1,JBM1,KBM1,IBP1,JBP1,KBP1
   INTEGER, POINTER, DIMENSION(:) :: I_LO,I_HI,J_LO,J_HI,K_LO,K_HI
   INTEGER, POINTER, DIMENSION(:,:,:) :: CGI,CGI2
   INTEGER, POINTER, DIMENSION(:) :: RGB
   REAL(EB) :: DXI,DETA,DZETA,RDXI,RDETA,RDZETA, &
      DXMIN,DXMAX,DYMIN,DYMAX,DZMIN,DZMAX, &
      XS,XF,YS,YF,ZS,ZF,RDXINT,RDYINT,RDZINT,CELL_SIZE
   REAL(EB), POINTER, DIMENSION(:) :: R,RC,X,Y,Z,XC,YC,ZC,HX,HY,HZ, &
            DX,RDX,DXN,RDXN,DY,RDY,DYN,RDYN,DZ,RDZ,DZN,RDZN, &
            CELLSI,CELLSJ,CELLSK,RREDX,RREDY,RREDZ,RRN
   REAL(FB), POINTER, DIMENSION(:) :: XPLT,YPLT,ZPLT
 
   INTEGER :: N_OBST
   TYPE(OBSTRUCTION_TYPE), POINTER, DIMENSION(:) :: OBSTRUCTION
 
   INTEGER :: N_VENT
   TYPE(VENTS_TYPE), POINTER, DIMENSION(:) :: VENTS
 
   INTEGER, POINTER, DIMENSION(:,:,:) :: CELL_INDEX
   INTEGER, POINTER, DIMENSION(:) :: I_CELL,J_CELL,K_CELL,OBST_INDEX_C
   INTEGER, POINTER, DIMENSION(:,:) :: WALL_INDEX
   LOGICAL, POINTER, DIMENSION(:) :: SOLID
 
   INTEGER :: NWC,NEWC,NDWC,NVWC,CELL_COUNT,WALL_COUNTER
   REAL(EB) :: BC_CLOCK
   REAL(EB), POINTER, DIMENSION(:,:) :: MASSFLUX,AWMPUA,WMPUA,WCPUA
   REAL(EB), POINTER, DIMENSION(:,:) :: RHODW,YY_W,EDGE_INTERPOLATION_FACTOR
   REAL(EB), POINTER, DIMENSION(:)   :: XW,YW,ZW,TW,AW,RAW,UW0,DUWDT,RDN,MASS_LOSS, &
            QRADIN,QRADOUT,EW,KW,QCONF,AREA_ADJUST,RHO_W,TMP_W,RSUM_W, &
            TMP_F,TMP_B,HEAT_TRANS_COEF,D_CORR,DS_CORR,DUDT_AVG,DVDT_AVG,DWDT_AVG,UVW_SAVE
   REAL(EB), POINTER, DIMENSION(:) :: E_WALL,ACTUAL_BURN_RATE
   REAL(EB), POINTER, DIMENSION(:) :: UW,UWS
   INTEGER, POINTER, DIMENSION(:,:) :: IJKW
   INTEGER, POINTER, DIMENSION(:) :: BOUNDARY_TYPE,NPPCW,OBST_INDEX_W,WALL_INDEX_BACK,VENT_INDEX,IBC_ORIG
 
   TYPE(WALL_TYPE), POINTER, DIMENSION(:) :: WALL
   TYPE(OMESH_TYPE), POINTER, DIMENSION(:) :: OMESH
   TYPE(DROPLET_TYPE), POINTER, DIMENSION(:) :: DROPLET
   INTEGER :: NLP,NLPDIM
   TYPE(HUMAN_TYPE), POINTER, DIMENSION(:) :: HUMAN
   INTEGER :: N_HUMANS,N_HUMANS_DIM
   TYPE(HUMAN_GRID_TYPE), POINTER, DIMENSION(:,:) :: HUMAN_GRID
 
   INTEGER :: N_SLCF
   TYPE(SLICE_TYPE), POINTER, DIMENSION(:) :: SLICE
 
   INTEGER, POINTER, DIMENSION(:,:) :: INC
   INTEGER :: NPATCH
 
   REAL(EB), POINTER, DIMENSION(:,:,:,:) :: UIID
   INTEGER :: RAD_CALL_COUNTER,ANGLE_INC_COUNTER
 
   REAL(EB) :: RHO_AVG
 
   INTEGER, POINTER, DIMENSION(:,:,:) :: INTERPOLATED_MESH
 
   CHARACTER(80), POINTER, DIMENSION(:) :: STRING
   INTEGER :: N_STRINGS,N_STRINGS_MAX
 
END TYPE MESH_TYPE
 
TYPE (MESH_TYPE), SAVE, DIMENSION(:), ALLOCATABLE, TARGET :: MESHES
 
END MODULE MESH_VARIABLES
 
 
MODULE MESH_POINTERS
 
USE PRECISION_PARAMETERS
USE MESH_VARIABLES
IMPLICIT NONE
 
REAL(EB), POINTER, DIMENSION(:,:,:) :: &
          U,V,W,US,VS,WS,DDDT,D,DS,H,HP,FVX,FVY,FVZ,RHO,RHOS, &
          MU,TMP,Q,Q_AVG,FRHO,KAPPA,QR,QR_W,UII,RSUM,Y_SUM,Z_SUM,D_VAP
REAL(EB), POINTER, DIMENSION(:,:,:,:) :: FRHOYY
REAL(EB), POINTER, DIMENSION(:,:,:,:) :: YY,YYS,DEL_RHO_D_DEL_Y,AVG_DROP_DEN,AVG_DROP_TMP,AVG_DROP_RAD 
REAL(EB), POINTER, DIMENSION(:,:) :: UVW_GHOST
REAL(EB), POINTER :: POIS_PTB,POIS_ERR
REAL(EB), POINTER, DIMENSION(:) :: SAVE1,SAVE2,WORK
REAL(EB), POINTER, DIMENSION(:,:,:) :: PRHS
REAL(EB), POINTER, DIMENSION(:,:) :: BXS,BXF,BYS,BYF,BZS,BZF, BXST,BXFT,BYST,BYFT,BZST,BZFT
INTEGER, POINTER :: LSAVE,LWORK,LBC,MBC,NBC,ITRN,JTRN,KTRN,IPS
REAL(EB), POINTER, DIMENSION(:) :: P_0,RHO_0,TMP_0,D_PBAR_DT,D_PBAR_S_DT,U_LEAK,U_DUCT
REAL(EB), POINTER, DIMENSION(:,:) :: PBAR,PBAR_S,R_PBAR,LEAK_AREA,FDS_LEAK_AREA
INTEGER, POINTER, DIMENSION(:,:,:) :: PRESSURE_ZONE
INTEGER, POINTER, DIMENSION(:) :: PRESSURE_ZONE_WALL
REAL(EB), POINTER, DIMENSION(:,:,:) :: WORK1,WORK2,WORK3,WORK4,WORK5,WORK6,WORK7

REAL(EB), POINTER, DIMENSION(:) :: SMIN_SAVE,SMAX_SAVE
REAL(EB), POINTER, DIMENSION(:,:,:) :: SCALAR_SAVE1
REAL(EB), POINTER, DIMENSION(:,:,:,:) :: SCALAR_SAVE2,SCALAR_SAVE3

REAL(EB), POINTER, DIMENSION(:) :: WALL_WORK1,WALL_WORK2
REAL(FB), POINTER, DIMENSION(:,:,:,:) :: QQ
REAL(FB), POINTER, DIMENSION(:,:) :: PP,PPN
INTEGER, POINTER, DIMENSION(:,:) :: IBK
INTEGER, POINTER, DIMENSION(:,:,:) :: IBLK
REAL(EB), POINTER :: DT,DTOLD,DTNEXT,DTINT,DTBX
REAL(EB), POINTER :: CFL,DIVMX,DIVMN,VN,RESMAX
INTEGER, POINTER :: ICFL,JCFL,KCFL,IMX,JMX,KMX,IMN,JMN,KMN,I_VN,J_VN,K_VN,IRM,JRM,KRM
INTEGER, POINTER :: N_EDGES
INTEGER, POINTER, DIMENSION(:,:) :: IJKE,EDGE_INDEX
REAL(EB), POINTER, DIMENSION(:) :: TAU_E,OME_E
INTEGER, POINTER, DIMENSION(:,:) :: EDGE_TYPE
INTEGER, POINTER :: IBAR,JBAR,KBAR,IBAR2,JBAR2,KBAR2,IBM1,JBM1,KBM1,IBP1,JBP1,KBP1
INTEGER, POINTER, DIMENSION(:) :: I_LO,I_HI,J_LO,J_HI,K_LO,K_HI
INTEGER, POINTER, DIMENSION(:,:,:) :: CGI,CGI2
INTEGER, POINTER, DIMENSION(:) :: RGB
REAL(EB), POINTER :: DXI,DETA,DZETA,RDXI,RDETA,RDZETA, &
   DXMIN,DXMAX,DYMIN,DYMAX,DZMIN,DZMAX, &
   XS,XF,YS,YF,ZS,ZF,RDXINT,RDYINT,RDZINT,CELL_SIZE
REAL(EB), POINTER, DIMENSION(:) :: R,RC,X,Y,Z,XC,YC,ZC,HX,HY,HZ, &
           DX,RDX,DXN,RDXN,DY,RDY,DYN,RDYN,DZ,RDZ,DZN,RDZN, &
           CELLSI,CELLSJ,CELLSK,RREDX,RREDY,RREDZ,RRN
REAL(FB), POINTER, DIMENSION(:) :: XPLT,YPLT,ZPLT
INTEGER, POINTER :: N_OBST
TYPE(OBSTRUCTION_TYPE), POINTER, DIMENSION(:) :: OBSTRUCTION
INTEGER, POINTER :: N_VENT
TYPE(VENTS_TYPE), POINTER, DIMENSION(:) :: VENTS
INTEGER, POINTER, DIMENSION(:,:,:) :: CELL_INDEX
INTEGER, POINTER, DIMENSION(:) :: I_CELL,J_CELL,K_CELL,OBST_INDEX_C
INTEGER, POINTER, DIMENSION(:,:) :: WALL_INDEX
LOGICAL, POINTER, DIMENSION(:) :: SOLID
INTEGER, POINTER :: NWC,NEWC,NDWC,NVWC,CELL_COUNT,WALL_COUNTER
REAL(EB),POINTER :: BC_CLOCK
REAL(EB), POINTER, DIMENSION(:,:) :: MASSFLUX,AWMPUA,WMPUA,WCPUA
REAL(EB), POINTER, DIMENSION(:,:) :: RHODW,YY_W,EDGE_INTERPOLATION_FACTOR
REAL(EB), POINTER, DIMENSION(:)   :: XW,YW,ZW,TW,AW,RAW,UW0,DUWDT,RDN,MASS_LOSS, &
           QRADIN,QRADOUT,EW,KW,QCONF,AREA_ADJUST,RHO_W,TMP_W,RSUM_W, &
           TMP_F,TMP_B,HEAT_TRANS_COEF,D_CORR,DS_CORR,DUDT_AVG,DVDT_AVG,DWDT_AVG,UVW_SAVE
REAL(EB), POINTER, DIMENSION(:) :: E_WALL,ACTUAL_BURN_RATE
REAL(EB), POINTER, DIMENSION(:) :: UW,UWS
INTEGER, POINTER, DIMENSION(:,:) :: IJKW
INTEGER, POINTER, DIMENSION(:) :: BOUNDARY_TYPE,NPPCW,OBST_INDEX_W,WALL_INDEX_BACK,VENT_INDEX,IBC_ORIG
TYPE(WALL_TYPE), POINTER, DIMENSION(:) :: WALL
TYPE(OMESH_TYPE), POINTER, DIMENSION(:) :: OMESH
TYPE(DROPLET_TYPE), POINTER, DIMENSION(:) :: DROPLET
INTEGER, POINTER :: NLP,NLPDIM
TYPE(HUMAN_TYPE), POINTER, DIMENSION(:) :: HUMAN
INTEGER, POINTER :: N_HUMANS,N_HUMANS_DIM
TYPE(HUMAN_GRID_TYPE), POINTER, DIMENSION(:,:) :: HUMAN_GRID
INTEGER, POINTER :: N_SLCF
TYPE(SLICE_TYPE), POINTER, DIMENSION(:) :: SLICE
INTEGER, POINTER, DIMENSION(:,:) :: INC
INTEGER, POINTER :: NPATCH
REAL(EB), POINTER, DIMENSION(:,:,:,:) :: UIID
INTEGER,  POINTER :: RAD_CALL_COUNTER,ANGLE_INC_COUNTER
REAL(EB), POINTER :: RHO_AVG
INTEGER, POINTER, DIMENSION(:,:,:) :: INTERPOLATED_MESH
CHARACTER(80), POINTER, DIMENSION(:) :: STRING
INTEGER, POINTER :: N_STRINGS,N_STRINGS_MAX

CONTAINS
 
 
SUBROUTINE POINT_TO_MESH(NM)

! Local names for MESH variables point to Global names
 
INTEGER, INTENT(IN) ::  NM
TYPE (MESH_TYPE), POINTER :: M
 
M=>MESHES(NM)
U=>M%U
V=>M%V
W=>M%W
US=>M%US
VS=>M%VS
WS=>M%WS
DDDT=>M%DDDT
D=>M%D
DS=>M%DS
H=>M%H 
HP=>M%HP
FVX=>M%FVX
FVY=>M%FVY
FVZ=>M%FVZ  
RHO=>M%RHO
RHOS=>M%RHOS
TMP=>M%TMP
FRHO=>M%FRHO
FRHOYY=>M%FRHOYY
MU=>M%MU
Q=>M%Q
Q_AVG=>M%Q_AVG
QR=>M%QR
QR_W=>M%QR_W
KAPPA=>M%KAPPA 
UII=>M%UII 
AVG_DROP_DEN=>M%AVG_DROP_DEN
AVG_DROP_TMP=>M%AVG_DROP_TMP
AVG_DROP_RAD=>M%AVG_DROP_RAD
D_VAP=>M%D_VAP
RSUM=>M%RSUM
Y_SUM=>M%Y_SUM
Z_SUM=>M%Z_SUM
YY=>M%YY
YYS=>M%YYS
DEL_RHO_D_DEL_Y=>M%DEL_RHO_D_DEL_Y
UVW_GHOST=>M%UVW_GHOST
POIS_PTB=>M%POIS_PTB
POIS_ERR=>M%POIS_ERR
SAVE1=>M%SAVE1
SAVE2=>M%SAVE2
WORK=>M%WORK
LSAVE=>M%LSAVE
LWORK=>M%LWORK
PRHS=>M%PRHS
BXS=>M%BXS
BXF=>M%BXF 
BYS=>M%BYS
BYF=>M%BYF 
BZS=>M%BZS
BZF=>M%BZF 
BXST=>M%BXST
BXFT=>M%BXFT 
BYST=>M%BYST
BYFT=>M%BYFT 
BZST=>M%BZST
BZFT=>M%BZFT 
LBC=>M%LBC
MBC=>M%MBC
NBC=>M%NBC 
ITRN=>M%ITRN
JTRN=>M%JTRN
KTRN=>M%KTRN
IPS=>M%IPS
U_LEAK=>M%U_LEAK
U_DUCT=>M%U_DUCT
LEAK_AREA=>M%LEAK_AREA
FDS_LEAK_AREA=>M%FDS_LEAK_AREA
D_PBAR_DT=>M%D_PBAR_DT
D_PBAR_S_DT=>M%D_PBAR_S_DT
PBAR=>M%PBAR
PBAR_S=>M%PBAR_S
R_PBAR=>M%R_PBAR
P_0=>M%P_0
RHO_0=>M%RHO_0
TMP_0=>M%TMP_0
PRESSURE_ZONE=>M%PRESSURE_ZONE
PRESSURE_ZONE_WALL=>M%PRESSURE_ZONE_WALL
WORK1=>M%WORK1
WORK2=>M%WORK2
WORK3=>M%WORK3 
WORK4=>M%WORK4
WORK5=>M%WORK5
WORK6=>M%WORK6 
WORK7=>M%WORK7

SCALAR_SAVE1=>M%SCALAR_SAVE1
SCALAR_SAVE2=>M%SCALAR_SAVE2
SCALAR_SAVE3=>M%SCALAR_SAVE3
SMIN_SAVE => M%SMIN_SAVE
SMAX_SAVE => M%SMAX_SAVE
DTBX => M%DTBX

WALL_WORK1=>M%WALL_WORK1
WALL_WORK2=>M%WALL_WORK2
QQ=>M%QQ
PP=>M%PP
PPN=>M%PPN
IBK=>M%IBK
IBLK=>M%IBLK
DT=>M%DT
DTOLD=>M%DTOLD
DTNEXT=>M%DTNEXT
DTINT=>M%DTINT
CFL=>M%CFL
DIVMX=>M%DIVMX
VN=>M%VN
RESMAX=>M%RESMAX
DIVMN=>M%DIVMN
ICFL=>M%ICFL
JCFL=>M%JCFL
KCFL=>M%KCFL 
IMX=>M%IMX
JMX=>M%JMX
KMX=>M%KMX
IMN=>M%IMN
JMN=>M%JMN
KMN=>M%KMN
IRM=>M%IRM
JRM=>M%JRM
KRM=>M%KRM
I_VN=>M%I_VN
J_VN=>M%J_VN
K_VN=>M%K_VN
N_EDGES=>M%N_EDGES
IJKE=>M%IJKE
EDGE_INDEX=>M%EDGE_INDEX
TAU_E=>M%TAU_E
OME_E=>M%OME_E
EDGE_TYPE=>M%EDGE_TYPE
IBAR=>M%IBAR
JBAR=>M%JBAR
KBAR=>M%KBAR 
IBAR2=>M%IBAR2
JBAR2=>M%JBAR2
KBAR2=>M%KBAR2
IBM1=>M%IBM1
JBM1=>M%JBM1
KBM1=>M%KBM1 
IBP1=>M%IBP1
JBP1=>M%JBP1
KBP1=>M%KBP1 
I_LO=>M%I_LO
I_HI=>M%I_HI 
J_LO=>M%J_LO
J_HI=>M%J_HI 
K_LO=>M%K_LO
K_HI=>M%K_HI 
CGI=>M%CGI 
CGI2=>M%CGI2
RGB=>M%RGB
DXI=>M%DXI
DETA=>M%DETA
DZETA=>M%DZETA 
RDXI=>M%RDXI
RDETA=>M%RDETA
RDZETA=>M%RDZETA 
DXMIN=>M%DXMIN
DXMAX=>M%DXMAX 
DYMIN=>M%DYMIN
DYMAX=>M%DYMAX 
DZMIN=>M%DZMIN
DZMAX=>M%DZMAX 
CELL_SIZE=>M%CELL_SIZE
XS=>M%XS 
XF=>M%XF 
YS=>M%YS
YF=>M%YF 
ZS=>M%ZS 
ZF=>M%ZF 
RDXINT=>M%RDXINT
RDYINT=>M%RDYINT
RDZINT=>M%RDZINT 
R=>M%R
RC=>M%RC
X=>M%X
Y=>M%Y
Z=>M%Z 
XC=>M%XC
YC=>M%YC
ZC=>M%ZC
HX=>M%HX
HY=>M%HY
HZ=>M%HZ
DX=>M%DX
DY=>M%DY
DZ=>M%DZ 
DXN=>M%DXN
DYN=>M%DYN
DZN=>M%DZN
RDX=>M%RDX
RDY=>M%RDY
RDZ=>M%RDZ 
RDXN=>M%RDXN
RDYN=>M%RDYN
RDZN=>M%RDZN
CELLSI=>M%CELLSI
CELLSJ=>M%CELLSJ
CELLSK=>M%CELLSK 
RREDX=>M%RREDX
RREDY=>M%RREDY
RREDZ=>M%RREDZ 
RRN=>M%RRN
XPLT=>M%XPLT
YPLT=>M%YPLT
ZPLT=>M%ZPLT 
N_OBST=>M%N_OBST
OBSTRUCTION=>M%OBSTRUCTION
N_VENT=>M%N_VENT
VENTS=>M%VENTS
CELL_INDEX=>M%CELL_INDEX
I_CELL=>M%I_CELL
J_CELL=>M%J_CELL
K_CELL=>M%K_CELL
OBST_INDEX_C=>M%OBST_INDEX_C
WALL_INDEX=>M%WALL_INDEX
SOLID=>M%SOLID 
NWC=>M%NWC
NEWC=>M%NEWC
NDWC=>M%NDWC
NVWC=>M%NVWC
CELL_COUNT=>M%CELL_COUNT
WALL_COUNTER=>M%WALL_COUNTER
BC_CLOCK=>M%BC_CLOCK
MASSFLUX=>M%MASSFLUX
RHODW=>M%RHODW
YY_W=>M%YY_W
TMP_F=>M%TMP_F
TMP_B=>M%TMP_B 
HEAT_TRANS_COEF=>M%HEAT_TRANS_COEF
UVW_SAVE=>M%UVW_SAVE
D_CORR=>M%D_CORR
DS_CORR=>M%DS_CORR
DUDT_AVG=>M%DUDT_AVG
DVDT_AVG=>M%DVDT_AVG
DWDT_AVG=>M%DWDT_AVG
XW=>M%XW
YW=>M%YW
ZW=>M%ZW
TW=>M%TW
AWMPUA=>M%AWMPUA 
AW=>M%AW
WMPUA=>M%WMPUA
WCPUA=>M%WCPUA
RAW=>M%RAW
UW0=>M%UW0
DUWDT=>M%DUWDT
RDN=>M%RDN
MASS_LOSS=>M%MASS_LOSS
EW=>M%EW
KW=>M%KW 
QRADIN=>M%QRADIN
QRADOUT=>M%QRADOUT
QCONF=>M%QCONF
AREA_ADJUST=>M%AREA_ADJUST
RHO_W=>M%RHO_W
TMP_W=>M%TMP_W
RSUM_W=>M%RSUM_W
E_WALL=>M%E_WALL
ACTUAL_BURN_RATE=>M%ACTUAL_BURN_RATE
UW=>M%UW
UWS=>M%UWS
OBST_INDEX_W=>M%OBST_INDEX_W
VENT_INDEX=>M%VENT_INDEX
IBC_ORIG=>M%IBC_ORIG
IJKW=>M%IJKW
EDGE_INTERPOLATION_FACTOR=>M%EDGE_INTERPOLATION_FACTOR
BOUNDARY_TYPE=>M%BOUNDARY_TYPE
WALL_INDEX_BACK=>M%WALL_INDEX_BACK
NPPCW=>M%NPPCW
WALL=>M%WALL
OMESH=>M%OMESH
DROPLET =>M%DROPLET  
NLP=>M%NLP 
NLPDIM=>M%NLPDIM
HUMAN =>M%HUMAN  
N_HUMANS=>M%N_HUMANS  
N_HUMANS_DIM=>M%N_HUMANS_DIM
HUMAN_GRID =>M%HUMAN_GRID
N_SLCF=>M%N_SLCF
SLICE=>M%SLICE
INC=>M%INC
NPATCH=>M%NPATCH
UIID=>M%UIID 
RAD_CALL_COUNTER=>M%RAD_CALL_COUNTER
ANGLE_INC_COUNTER=>M%ANGLE_INC_COUNTER
RHO_AVG=>M%RHO_AVG
INTERPOLATED_MESH => M%INTERPOLATED_MESH
STRING=>M%STRING 
N_STRINGS=>M%N_STRINGS 
N_STRINGS_MAX=>M%N_STRINGS_MAX
 
END SUBROUTINE POINT_TO_MESH

SUBROUTINE GET_REV_mesh(MODULE_REV,MODULE_DATE)
INTEGER,INTENT(INOUT) :: MODULE_REV
CHARACTER(255),INTENT(INOUT) :: MODULE_DATE

WRITE(MODULE_DATE,'(A)') meshrev(INDEX(meshrev,':')+1:LEN_TRIM(meshrev)-2)
READ (MODULE_DATE,'(I5)') MODULE_REV
WRITE(MODULE_DATE,'(A)') meshdate

END SUBROUTINE GET_REV_mesh

 
END MODULE MESH_POINTERS


MODULE DEVICE_VARIABLES
 
USE PRECISION_PARAMETERS
IMPLICIT NONE

CHARACTER(255), PARAMETER :: devcid='$Id$'
CHARACTER(255), PARAMETER :: devcrev='$Revision$'
CHARACTER(255), PARAMETER :: devcdate='$Date$'

LOGICAL :: GAS_CELL_RAD_FLUX=.FALSE.,CONDUIT=.FALSE.
INTEGER, POINTER, DIMENSION(:) :: GAS_CELL_RAD_DEVC_INDEX
INTEGER :: N_GAS_CELL_RAD_DEVC=0

TYPE PROPERTY_TYPE
   REAL(EB) :: BEAD_DIAMETER,BEAD_EMISSIVITY,RTI,ACTIVATION_TEMPERATURE,ACTIVATION_OBSCURATION, &
               ALPHA_E,ALPHA_C,BETA_E,BETA_C,CHARACTERISTIC_VELOCITY,DROPLET_VELOCITY,FLOW_RATE,FLOW_TAU,GAUGE_TEMPERATURE, &
               INITIAL_TEMPERATURE,K_FACTOR,C_FACTOR,OPERATING_PRESSURE,OFFSET,SPRAY_ANGLE(2), &
               CABLE_DIAMETER,CABLE_JACKET_THICKNESS,CABLE_FAILURE_TEMPERATURE,CABLE_MASS_PER_LENGTH, &
               CONDUIT_DIAMETER,CONDUIT_THICKNESS
   INTEGER  :: PDPA_M=3,PDPA_N=2
   LOGICAL  :: PDPA_U=.FALSE.,PDPA_V=.FALSE.,PDPA_W=.FALSE.,PDPA_COUNT=.FALSE.
   REAL(EB) :: PDPA_START=0._EB,PDPA_END=1.E6,PDPA_RADIUS=0.1_EB
   REAL, POINTER, DIMENSION(:) :: TABLE_ROW
   INTEGER  :: PART_INDEX,FLOW_RAMP_INDEX,SPRAY_PATTERN_INDEX,SPEC_INDEX=0
   CHARACTER(30) :: SMOKEVIEW_ID,PART_ID,ID,QUANTITY,TABLE_ID,SPEC_ID='null'
END TYPE PROPERTY_TYPE

TYPE DEVICE_TYPE
   REAL(EB) :: T,X,Y,Z,X1,X2,Y1,Y2,Z1,Z2,INSTANT_VALUE,VALUE,DEPTH,TMP_L,Y_C,OBSCURATION,DELAY,ROTATION,&
               SETPOINT, T_CHANGE=1000000._EB,BYPASS_FLOWRATE,DT,TOTAL_FLOWRATE,FLOWRATE
   REAL(EB) :: PDPA_NUMER=0._EB,PDPA_DENUM=0._EB
   INTEGER  :: PDPA_GROUP
   REAL(EB), POINTER, DIMENSION(:) :: D_PATH,TIME_ARRAY
   REAL(EB), POINTER, DIMENSION(:,:) :: YY_SOOT, ILW
   REAL(EB), DIMENSION(3) :: ORIENTATION
   INTEGER  :: OUTPUT_INDEX,IOR,IW,COUNT,ORDINAL,I,J,K,MESH,I1=-1,I2=-1,J1=-1,J2=-1,K1=-1,K2=-1,I_DEPTH,N_PATH,N_T_E,PROP_INDEX,&
               TRIP_DIRECTION,CTRL_INDEX,N_INPUTS,VIRTUAL_WALL_INDEX=0,SURF_INDEX=-1,SPEC_INDEX=0,PART_INDEX=0
   INTEGER, POINTER, DIMENSION(:) :: DEVC_INDEX
   INTEGER, POINTER, DIMENSION(:) :: I_PATH,J_PATH,K_PATH
   REAL(EB),  POINTER, DIMENSION(:) :: Y_E,T_E
   CHARACTER(30) :: ID,PROP_ID,QUANTITY,CTRL_ID,DEVC_ID,STATISTICS='null',SURF_ID,PART_ID='null',SPEC_ID='null',MATL_ID='null', &
                    SMOKEVIEW_BAR_LABEL
   CHARACTER(60) :: SMOKEVIEW_LABEL
   LOGICAL :: INITIAL_STATE,CURRENT_STATE,LATCH,PRIOR_STATE,GAS_CELL_RAD_FLUX=.FALSE.
END TYPE DEVICE_TYPE

TYPE CABLE_TYPE
   REAL(EB) :: DIAMETER,FAILURE_TEMPERATURE,MASS_PER_LENGTH
   INTEGER :: PROP_INDEX
END TYPE CABLE_TYPE

! Device arrays

INTEGER :: N_PROP,N_DEVC,N_CABL=0
TYPE (PROPERTY_TYPE),  DIMENSION(:), ALLOCATABLE, TARGET :: PROPERTY
TYPE (DEVICE_TYPE),  DIMENSION(:), ALLOCATABLE, TARGET :: DEVICE
TYPE (CABLE_TYPE),  DIMENSION(:), ALLOCATABLE, TARGET :: CABLE

CONTAINS

SUBROUTINE GET_REV_devc(MODULE_REV,MODULE_DATE)
INTEGER,INTENT(INOUT) :: MODULE_REV
CHARACTER(255),INTENT(INOUT) :: MODULE_DATE

WRITE(MODULE_DATE,'(A)') devcrev(INDEX(devcrev,':')+1:LEN_TRIM(devcrev)-2)
READ (MODULE_DATE,'(I5)') MODULE_REV
WRITE(MODULE_DATE,'(A)') devcdate

END SUBROUTINE GET_REV_devc

END MODULE DEVICE_VARIABLES


MODULE CONTROL_VARIABLES
! Variables for evaluating control functions
USE PRECISION_PARAMETERS

IMPLICIT NONE

TYPE CONTROL_TYPE
   LOGICAL :: SPECIFIED_STATE=.FALSE.,INITIAL_STATE=.FALSE.,CURRENT_STATE=.FALSE.,PRIOR_STATE=.FALSE.,LATCH=.TRUE.,UPDATED=.FALSE.
   INTEGER :: CONTROL_INDEX=0,CYCLES=1,N_INPUTS=0,RAMP_INDEX=0,MESH=1,N=1,ON_BOUND=0
   INTEGER, POINTER, DIMENSION (:) :: INPUT,INPUT_TYPE
   REAL(EB) :: SETPOINT(2)=1000000._EB, DELAY=0._EB, T_CHANGE=1000000._EB ,CYCLE_TIME=1000000._EB
   CHARACTER(30) :: ID='null',RAMP_ID='null',INPUT_ID(40)='null'
END TYPE CONTROL_TYPE

TYPE (CONTROL_TYPE),  DIMENSION(:), ALLOCATABLE, TARGET :: CONTROL

INTEGER, PARAMETER :: AND_GATE=1, OR_GATE=2, XOR_GATE=3, X_OF_N_GATE=4, TIME_DELAY=5, DEADBAND=6, CYCLING=7, &
                      CUSTOM=8,KILL=9,CORE_DUMP=10,DEVICE_INPUT=1, CONTROL_INPUT=2

INTEGER :: N_CTRL, N_CTRL_FILES

END MODULE CONTROL_VARIABLES
